#!/usr/bin/env bash
# =============================================================================
#  aperod-watchdog-set-interval — apply WATCHDOG_INTERVAL_SECS from
#  /etc/aperod/watchdog.env to the aperod-node-watchdog.timer unit.
#
#  Usage (as root):
#    sudo aperod-watchdog-set-interval
#
#  The script:
#    1. Reads WATCHDOG_INTERVAL_SECS from /etc/aperod/watchdog.env
#       (defaults to 60 if the variable is absent or invalid).
#    2. Writes a systemd drop-in that overrides OnBootSec / OnUnitActiveSec.
#    3. Runs systemctl daemon-reload and restarts the timer — no manual
#       step required on the operator's side.
#
#  To restore the hard-coded default simply remove the drop-in:
#    sudo rm -f /etc/systemd/system/aperod-node-watchdog.timer.d/interval.conf
#    sudo systemctl daemon-reload
#    sudo systemctl restart aperod-node-watchdog.timer
#
#  Testing: set _APEROD_TEST=1 to skip the root check and allow path
#  overrides via ENV_FILE and DROPIN_DIR environment variables.
# =============================================================================
set -euo pipefail

# ── Path defaults (overridable for tests) ────────────────────────────────────
ENV_FILE="${ENV_FILE:-/etc/aperod/watchdog.env}"
DROPIN_DIR="${DROPIN_DIR:-/etc/systemd/system/aperod-node-watchdog.timer.d}"
DROPIN_FILE="${DROPIN_DIR}/interval.conf"
DEFAULT_INTERVAL=60

# ── Require root (skip in test mode) ─────────────────────────────────────────
if [[ "${_APEROD_TEST:-0}" != "1" ]] && [[ $(id -u) -ne 0 ]]; then
  echo "[ERR] Run as root: sudo aperod-watchdog-set-interval" >&2
  exit 1
fi

# ── Read interval from env file ───────────────────────────────────────────────
# Strip leading whitespace, quotes, and inline # comments so that lines like
#   WATCHDOG_INTERVAL_SECS=15   # faster detection for HA setups
# are parsed correctly as "15".
INTERVAL="${DEFAULT_INTERVAL}"
if [[ -f "${ENV_FILE}" ]]; then
  RAW=$(grep -E '^[[:space:]]*WATCHDOG_INTERVAL_SECS[[:space:]]*=' "${ENV_FILE}" \
        | tail -1 \
        | sed 's/^[^=]*=//' \
        | sed 's/[[:space:]]*#.*//' \
        | tr -d '[:space:]"'"'" 2>/dev/null || true)
  if [[ -n "${RAW}" && "${RAW}" =~ ^[0-9]+$ && "${RAW}" -ge 5 ]]; then
    INTERVAL="${RAW}"
  elif [[ -n "${RAW}" ]]; then
    echo "[WARN] WATCHDOG_INTERVAL_SECS='${RAW}' is not a valid integer >= 5. Using default ${DEFAULT_INTERVAL} s." >&2
  fi
fi

echo "[INFO] Setting watchdog interval to ${INTERVAL} s ..."

# ── Write drop-in ─────────────────────────────────────────────────────────────
mkdir -p "${DROPIN_DIR}"
cat > "${DROPIN_FILE}" <<DROPIN
# Auto-generated by aperod-watchdog-set-interval — do not edit by hand.
# To change the interval:
#   1. Edit /etc/aperod/watchdog.env  (WATCHDOG_INTERVAL_SECS=<seconds>)
#   2. Run: sudo aperod-watchdog-set-interval
[Timer]
# Clear any previously inherited values before setting the new ones.
OnBootSec=
OnUnitActiveSec=
OnBootSec=${INTERVAL}
OnUnitActiveSec=${INTERVAL}
DROPIN

# ── Reload systemd and restart the timer ──────────────────────────────────────
systemctl daemon-reload
systemctl restart aperod-node-watchdog.timer

echo "[OK]  Watchdog timer restarted — interval is now ${INTERVAL} s."
echo "      Verify: systemctl list-timers aperod-node-watchdog.timer"
