#!/usr/bin/env bash
# =============================================================================
#  aperod-sched-restart-set-interval — write SCHED_RESTART_INTERVAL_SECS to
#  /etc/aperod/sched-restart.env and apply it to aperod-node-sched-restart.timer.
#
#  Usage (as root):
#    sudo aperod-sched-restart-set-interval [--interval=<seconds>]
#
#  Without --interval the script reads the existing value from sched-restart.env
#  (defaults to 10800 / 3 h if absent/invalid) and re-applies it to the timer.
#
#  With --interval=N the script:
#    1. Validates N (integer 3600–86400, i.e. 1 h – 24 h).
#    2. Writes SCHED_RESTART_INTERVAL_SECS=N to /etc/aperod/sched-restart.env
#       (creates the file / directory if absent; preserves other lines).
#    3. Writes a systemd drop-in that overrides OnBootSec / OnUnitActiveSec.
#    4. Runs systemctl daemon-reload and restarts the timer.
#
#  To restore the default (10800 s / 3 h) without a redeploy:
#    sudo rm -f /etc/systemd/system/aperod-node-sched-restart.timer.d/interval.conf
#    sudo systemctl daemon-reload
#    sudo systemctl restart aperod-node-sched-restart.timer
#
#  Testing: set _APEROD_TEST=1 to skip the root check and allow path
#  overrides via ENV_FILE and DROPIN_DIR environment variables.
# =============================================================================
set -euo pipefail

# ── Path defaults (overridable for tests) ─────────────────────────────────────
ENV_FILE="${ENV_FILE:-/etc/aperod/sched-restart.env}"
DROPIN_DIR="${DROPIN_DIR:-/etc/systemd/system/aperod-node-sched-restart.timer.d}"
DROPIN_FILE="${DROPIN_DIR}/interval.conf"
DEFAULT_INTERVAL=10800   # 3 hours

# ── Require root (skip in test mode) ──────────────────────────────────────────
if [[ "${_APEROD_TEST:-0}" != "1" ]] && [[ $(id -u) -ne 0 ]]; then
  echo "[ERR] Run as root: sudo aperod-sched-restart-set-interval" >&2
  exit 1
fi

# ── Parse optional --interval=N argument ──────────────────────────────────────
ARG_INTERVAL=""
for arg in "$@"; do
  if [[ "${arg}" =~ ^--interval=([0-9]+)$ ]]; then
    ARG_INTERVAL="${BASH_REMATCH[1]}"
  fi
done

# ── If --interval=N provided, write it to the env file first ──────────────────
if [[ -n "${ARG_INTERVAL}" ]]; then
  # Valid range: 3600 s (1 h) … 86400 s (24 h)
  if [[ "${ARG_INTERVAL}" -lt 3600 || "${ARG_INTERVAL}" -gt 86400 ]]; then
    echo "[ERR] --interval=${ARG_INTERVAL} is out of range (3600–86400)." >&2
    exit 1
  fi
  mkdir -p "$(dirname "${ENV_FILE}")"
  chmod 700 "$(dirname "${ENV_FILE}")"
  KEY_LINE="SCHED_RESTART_INTERVAL_SECS=${ARG_INTERVAL}"
  if [[ -f "${ENV_FILE}" ]] && grep -qE '^\s*SCHED_RESTART_INTERVAL_SECS\s*=' "${ENV_FILE}" 2>/dev/null; then
    sed -i "s|^\s*SCHED_RESTART_INTERVAL_SECS\s*=.*|${KEY_LINE}|" "${ENV_FILE}"
  else
    echo "${KEY_LINE}" >> "${ENV_FILE}"
  fi
  echo "[INFO] Wrote ${KEY_LINE} to ${ENV_FILE}"

  # Record the Unix-ms timestamp of this interval change so the API can detect
  # that the countdown base has shifted even before the next restart fires.
  TS_MS=$(( $(date +%s) * 1000 ))
  CHANGED_LINE="SCHED_RESTART_INTERVAL_CHANGED_AT=${TS_MS}"
  if [[ -f "${ENV_FILE}" ]] && grep -qE '^\s*SCHED_RESTART_INTERVAL_CHANGED_AT\s*=' "${ENV_FILE}" 2>/dev/null; then
    sed -i "s|^\s*SCHED_RESTART_INTERVAL_CHANGED_AT\s*=.*|${CHANGED_LINE}|" "${ENV_FILE}"
  else
    echo "${CHANGED_LINE}" >> "${ENV_FILE}"
  fi
  echo "[INFO] Wrote ${CHANGED_LINE} to ${ENV_FILE}"
fi

# ── Read interval from env file ───────────────────────────────────────────────
INTERVAL="${DEFAULT_INTERVAL}"
if [[ -f "${ENV_FILE}" ]]; then
  RAW=$(grep -E '^[[:space:]]*SCHED_RESTART_INTERVAL_SECS[[:space:]]*=' "${ENV_FILE}" \
        | tail -1 \
        | sed 's/^[^=]*=//' \
        | sed 's/[[:space:]]*#.*//' \
        | tr -d '[:space:]"'"'" 2>/dev/null || true)
  if [[ -n "${RAW}" && "${RAW}" =~ ^[0-9]+$ && "${RAW}" -ge 3600 ]]; then
    INTERVAL="${RAW}"
  elif [[ -n "${RAW}" ]]; then
    echo "[WARN] SCHED_RESTART_INTERVAL_SECS='${RAW}' is out of range (min 3600). Using default ${DEFAULT_INTERVAL} s." >&2
  fi
fi

INTERVAL_H=$(( INTERVAL / 3600 ))
echo "[INFO] Setting sched-restart interval to ${INTERVAL} s (${INTERVAL_H} h) ..."

# ── Write drop-in ──────────────────────────────────────────────────────────────
mkdir -p "${DROPIN_DIR}"
cat > "${DROPIN_FILE}" <<DROPIN
# Auto-generated by aperod-sched-restart-set-interval — do not edit by hand.
# To change the interval:
#   1. Edit /etc/aperod/sched-restart.env  (SCHED_RESTART_INTERVAL_SECS=<seconds>)
#   2. Run: sudo aperod-sched-restart-set-interval
[Timer]
# Clear previously inherited values before setting the new ones.
OnBootSec=
OnUnitActiveSec=
OnBootSec=${INTERVAL}
OnUnitActiveSec=${INTERVAL}
DROPIN

# ── Reload systemd (and optionally restart the timer) ────────────────────────
# APEROD_DROPIN_ONLY=1: write the drop-in and daemon-reload only.
# Used by install-node.sh on the no-primary-ip path so that a pre-existing
# enabled timer is not activated before aperod-join.sh has run.
systemctl daemon-reload
if [[ "${APEROD_DROPIN_ONLY:-0}" == "1" ]]; then
  echo "[OK]  Drop-in written and daemon reloaded (write-only mode; timer not restarted)."
  echo "      Interval will take effect when the timer is started by aperod-join.sh."
else
  systemctl restart aperod-node-sched-restart.timer
  echo "[OK]  Sched-restart timer restarted — interval is now ${INTERVAL} s (${INTERVAL_H} h)."
  echo "      Verify: systemctl list-timers aperod-node-sched-restart.timer"
fi
